noseList = [
    {code: 'nose0', desc: '얼굴 중심',},
    {code: 'nose1r', desc: '인중 시작점(오른쪽)',},
    {code: 'nose2r', desc: '콧볼(오른쪽)',},
    {code: 'nose3r', desc: '위콧대(오른쪽)',},
    {code: 'nose4r', desc: '콧구멍(오른쪽)',},
    {code: 'nose5r', desc: '코끝(오른쪽)',},
    {code: 'nose1l', desc: '인중 시작점(왼쪽)',},
    {code: 'nose2l', desc: '콧볼(왼쪽)',},
    {code: 'nose3l', desc: '위콧대(왼쪽)',},
    {code: 'nose4l', desc: '콧구멍(왼쪽)',},
    {code: 'nose5l', desc: '코끝(왼쪽)',},
]

eyesList = [
    {code: 'eye1r', desc: '눈앞머리(오른쪽)',},
    {code: 'eye2r', desc: '눈꼬리(오른쪽)',},
    {code: 'eye3r', desc: '아랫눈꺼풀 가장 낮은 점(오른쪽)',},
    {code: 'eye4r', desc: '윗눈꺼풀 가장 높은 점(오른쪽)',},
    {code: 'eye5r', desc: '눈동자(오른쪽)',},
    {code: 'eye6r', desc: '눈동자 기준 윗눈꺼풀(오른쪽)',},
    {code: 'eye7r', desc: '눈동자 기준 아래눈꺼풀(오른쪽)',},
    {code: 'eye8r', desc: '눈앞머리쪽 눈동자 끝(오른쪽)',},
    {code: 'eye9r', desc: '눈꼬리쪽 눈동자 끝(오른쪽)',},
    {code: 'eye10r', desc: '눈동자 기준 쌍커풀 라인(오른쪽)',},
    {code: 'eye11r', desc: '눈꼬리 기준 쌍커풀라인(오른쪽)',},
    {code: 'eye12r', desc: '눈동자 기준 애교살 지점(오른쪽)',},
    {code: 'eye1l', desc: '눈앞머리(왼쪽)',},
    {code: 'eye2l', desc: '눈꼬리(왼쪽)',},
    {code: 'eye3l', desc: '아랫눈꺼풀 가장 낮은 점(왼쪽)',},
    {code: 'eye4l', desc: '윗눈꺼풀 가장 높은 점(왼쪽)',},
    {code: 'eye5l', desc: '눈동자(왼쪽)',},
    {code: 'eye6l', desc: '눈동자 기준 윗눈꺼풀(왼쪽)',},
    {code: 'eye7l', desc: '눈동자 기준 아래눈꺼풀(왼쪽)',},
    {code: 'eye8l', desc: '눈앞머리쪽 눈동자 끝(왼쪽)',},
    {code: 'eye9l', desc: '눈꼬리쪽 눈동자 끝(왼쪽)',},
    {code: 'eye10l', desc: '눈동자 기준 쌍커풀 라인(왼쪽)',},
    {code: 'eye11l', desc: '눈꼬리 기준 쌍커풀라인(왼쪽)',},
    {code: 'eye12l', desc: '눈동자 기준 애교살 지점(왼쪽)',},
]

eyebrowsList = [
    {code: 'brow1r', desc: '눈썹머리 위(오른쪽)',},
    {code: 'brow2r', desc: '눈썹머리 아래(오른쪽)',},
    {code: 'brow3r', desc: '눈동자 기준 눈썹머리 위(오른쪽)',},
    {code: 'brow4r', desc: '눈동자 기준 눈썹머리 아래(오른쪽)',},
    {code: 'brow5r', desc: '눈썹중간 위(오른쪽)',},
    {code: 'brow6r', desc: '눈썹중간 아래(오른쪽)',},
    {code: 'brow7r', desc: '눈썹산 위(오른쪽)',},
    {code: 'brow8r', desc: '눈썹꼬리(오른쪽)',},
    {code: 'brow1l', desc: '눈썹머리 위(왼쪽)',},
    {code: 'brow2l', desc: '눈썹머리 아래(왼쪽)',},
    {code: 'brow3l', desc: '눈동자 기준 눈썹머리 위(왼쪽)',},
    {code: 'brow4l', desc: '눈동자 기준 눈썹머리 아래(왼쪽)',},
    {code: 'brow5l', desc: '눈썹중간 위(왼쪽)',},
    {code: 'brow6l', desc: '눈썹중간 아래(왼쪽)',},
    {code: 'brow7l', desc: '눈썹산 위(왼쪽)',},
    {code: 'brow8l', desc: '눈썹꼬리(왼쪽)',},
]

lipsList = [
    {code: 'lip0', desc: '윗입술 중간',},
    {code: 'lip1r', desc: '인중기준 윗입술라인(오른쪽)',},
    {code: 'lip2r', desc: '인중기준 입술 중간 라인(오른쪽)',},
    {code: 'lip3r', desc: '인중기준 아랫입술라인(오른쪽)',},
    {code: 'lip4r', desc: '입술산(오른쪽)',},
    {code: 'lip5r', desc: '콧볼 기준 윗입술라인(오른쪽)',},
    {code: 'lip6r', desc: '콧볼기준 아랫입술라인(오른쪽)',},
    {code: 'lip7r', desc: '입꼬리(오른쪽)',},
    {code: 'lip8r', desc: '콧구멍 기준 아랫입술라인(오른쪽)',},
    {code: 'lip1l', desc: '인중기준 윗입술라인(왼쪽)',},
    {code: 'lip2l', desc: '인중기준 입술 중간 라인(왼쪽)',},
    {code: 'lip3l', desc: '인중기준 아랫입술라인(왼쪽)',},
    {code: 'lip4l', desc: '입술산(왼쪽)',},
    {code: 'lip5l', desc: '콧볼 기준 윗입술라인(왼쪽)',},
    {code: 'lip6l', desc: '콧볼기준 아랫입술라인(왼쪽)',},
    {code: 'lip7l', desc: '입꼬리(왼쪽)',},
    {code: 'lip8l', desc: '콧구멍 기준 아랫입술라인(왼쪽)',},
]

facelineList = [
    {code: 'face1r', desc: '얼굴 가로너비(오른쪽)',},
    {code: 'face2r', desc: '인중기준 이마라인(오른쪽)',},
    {code: 'face3r', desc: '턱끝(오른쪽)',},
    {code: 'face4r', desc: '코끝기준 이마라인 오른쪽(오른쪽)',},
    {code: 'face5r', desc: '눈가운데 기준 이마라인(오른쪽)',},
    {code: 'face6r', desc: '눈썹산 기준 이마라인(오른쪽)',},
    {code: 'face7r', desc: '눈썹꼬리 기준 이마라인(오른쪽)',},
    {code: 'face8r', desc: '눈썹 앞머리 기준 이마라인(오른쪽)',},
    {code: 'face9r', desc: '인중기준 얼굴 가로 외곽(오른쪽)',},
    {code: 'face10r', desc: '인중선과 턱끝 중간 볼록(오른쪽)',},
    {code: 'face11r', desc: '눈앞머리 기준 얼굴 가로선(오른쪽)',},
    {code: 'face12r', desc: '눈썹꼬리 기준 얼굴 가로선(오른쪽)',},
    {code: 'face1l', desc: '얼굴 가로너비(왼쪽)',},
    {code: 'face2l', desc: '인중기준 이마라인(왼쪽)',},
    {code: 'face3l', desc: '턱끝(왼쪽)',},
    {code: 'face4l', desc: '코끝기준 이마라인 오른쪽(왼쪽)',},
    {code: 'face5l', desc: '눈가운데 기준 이마라인(왼쪽)',},
    {code: 'face6l', desc: '눈썹산 기준 이마라인(왼쪽)',},
    {code: 'face7l', desc: '눈썹꼬리 기준 이마라인(왼쪽)',},
    {code: 'face8l', desc: '눈썹 앞머리 기준 이마라인(왼쪽)',},
    {code: 'face9l', desc: '인중기준 얼굴 가로 외곽(왼쪽)',},
    {code: 'face10l', desc: '인중선과 턱끝 중간 볼록(왼쪽)',},
    {code: 'face11l', desc: '눈앞머리 기준 얼굴 가로선(왼쪽)',},
    {code: 'face12l', desc: '눈썹꼬리 기준 얼굴 가로선(왼쪽)',},
]

